### PR TITLE
Rework interface inheritance

### PR DESCRIPTION
**Pull request by gruberro**

### CODE REVIEW

**Comment by andrew-demb** [comment]
:+1:

**Comment by andrew-demb** [comment]
Notice about BC - if someone was declare implementation in code as

```php
use Gruberro\MongoDbMigrations;

class MyMigration implements
    MongoDbMigrations\ContextualMigrationInterface,
    MongoDbMigrations\MigrationInterface
```

Then they will receive in new version fatal
> PHP Fatal error:  Class MyMigration cannot implement previously implemented interface Gruberro\MongoDbMigrations\MigrationInterface in ...

**Comment by gruberro** [comment]
That's strange. I've tested exactly that... will check again because the tests itself are stable here... when the error occurs? While invoking the command or when executing the test suite?

**Comment by andrew-demb** [comment]
It can be reproduced when more special interface (contextual/run-always) are specified before common.

https://github.com/gruberro/php-mongo-migrations/compare/rework-interface-inheritance...andrew-demb:test-for-broken-rework-interface-inheritance?expand=1
On my branch tests failed while php trying to autoload this migration classes.

**Comment by alcaeus** [comment]
That is one of the problems with such inheritance chains. TBH, I see no problem NOT extending the common interface in the more specialised ones: you should always favour composition over inheritance. Yes, it may not make sense marking a class as `RunAlwaysMigration` without marking it as a migration, but that doesn't mean the interfaces need to extend.

**Comment by gruberro** [comment]
Since this change would introduce a bc break and I don't see this minor change as valuable for a new major version I'll close this PR and postpone the change to a later version. TY nevertheless @andrew-demb.

**Pull request closed without merging**
